server:
  AppVersion: 1.0.0
  Port: :5000
  Mode: Development
  ReadTimeout: 5
  WriteTimeout: 5
  CtxDefaultTimeout: 12

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: debug
