server:
  AppVersion: 1.0.0
  Port: :5000
  Mode: Development
  ReadTimeout: 10
  WriteTimeout: 10
  CtxDefaultTimeout: 12

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: console
  Level: info
