// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Antonio Martínez",
            "url": "https://github.com/AntonioMartinezFernandez",
            "email": "antonio@weffective.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/event-processor": {
            "post": {
                "description": "Event Processor Endpoint Validator",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event Processor"
                ],
                "summary": "Event Processor Endpoint Validator",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.EventProcessorValidationResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/event-processor/process": {
            "post": {
                "description": "Event Processor",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event Processor"
                ],
                "summary": "Event Processor",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.EventProcessorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/healthcheck": {
            "get": {
                "description": "Get healthcheck",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Healthcheck"
                ],
                "summary": "Get healthcheck",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Healthcheck"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        }
    },
    "definitions": {
        "models.EventProcessorResponse": {
            "type": "object",
            "required": [
                "response"
            ],
            "properties": {
                "response": {
                    "type": "string"
                }
            }
        },
        "models.EventProcessorValidationResponse": {
            "type": "object",
            "required": [
                "validated"
            ],
            "properties": {
                "validated": {
                    "type": "boolean"
                }
            }
        },
        "models.Healthcheck": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Hexagonal Go",
	Description:      "Hexagonal Go",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
